package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF004D99)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF1565C0)
val md_theme_light_onPrimaryContainer = Color(0xFFDAE5FF)
val md_theme_light_secondary = Color(0xFF5B5F61)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDDE0E2)
val md_theme_light_onSecondaryContainer = Color(0xFF181C1E)
val md_theme_light_tertiary = Color(0xFF813900)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFA64C00)
val md_theme_light_onTertiaryContainer = Color(0xFFFFDECE)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF93000A)
val md_theme_light_background = Color(0xFFF9F9FF)
val md_theme_light_onBackground = Color(0xFF191C21)
val md_theme_light_surface = Color(0xFFF9F9FF)
val md_theme_light_onSurface = Color(0xFF191C21)
val md_theme_light_surfaceVariant = Color(0xFFE1E2EA)
val md_theme_light_onSurfaceVariant = Color(0xFF44474E)
val md_theme_light_outline = Color(0xFF727783)
val md_theme_light_inverseOnSurface = Color(0xFFF0F0F8)
val md_theme_light_inverseSurface = Color(0xFF2E3135)
val md_theme_light_inversePrimary = Color(0xFFAEC6FF)
val md_theme_light_surfaceTint = Color(0xFF004D99)
val md_theme_light_outlineVariant = Color(0xFFC2C6D4)
val md_theme_light_scrim = Color(0xFF000000)

val SafetyOrange = Color(0xFFFF6F00)
